"""first_migration_schedule

Revision ID: 0b53af2fccf9
Revises: 
Create Date: 2026-05-11 20:17:18.119243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b53af2fccf9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=156), nullable=False),
    sa.Column('mail', sa.String(length=300), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False, comment='Ник'),
    sa.Column('code', sa.String(length=6), nullable=True, comment='Код для добавления в друзья'),
    sa.Column('account_confirmed', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('ix_users_account_code', 'users', ['code'], unique=False, schema='public')
    op.create_index('ix_users_account_confirmed', 'users', ['account_confirmed'], unique=False, schema='public')
    op.create_index('ix_users_account_name', 'users', ['name'], unique=False, schema='public')
    op.create_index('ix_users_account_nick', 'users', ['nickname'], unique=False, schema='public')
    op.create_index('ix_users_is_banned', 'users', ['is_banned'], unique=False, schema='public')
    op.create_table('celendar_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('DAY_OFF', 'WORKING_DAY', 'BUSY', 'MY_OWN_PLANS', 'FREE', 'PLAY', 'MEETING', 'TRIP', 'OTHER_EVENT', name='eventtype'), nullable=False),
    sa.Column('event_name', sa.String(length=56), nullable=True, comment='Название события'),
    sa.Column('event_desctiption', sa.String(length=500), nullable=True, comment='Описание события'),
    sa.Column('planning', sa.Enum('DEFINITELY', 'PLANNING_TO', 'MIGHT_GO', 'DEFINITELY_NOT', name='accuracy'), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('ix_calendar_planning', 'celendar_event', ['planning'], unique=False, schema='public')
    op.create_index('ix_calendar_type', 'celendar_event', ['type'], unique=False, schema='public')
    op.create_index('ix_calendar_user_date', 'celendar_event', ['user_id', 'event_date'], unique=False, schema='public')
    op.create_index(op.f('ix_public_celendar_event_event_date'), 'celendar_event', ['event_date'], unique=False, schema='public')
    op.create_table('friends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id_main', sa.Integer(), nullable=False),
    sa.Column('user_id_friend', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending | accepted | blocked | deleted'),
    sa.ForeignKeyConstraint(['user_id_friend'], ['public.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id_main'], ['public.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id_main', 'user_id_friend', name='uq_friend_pair'),
    schema='public'
    )
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('comments_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=256), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['public.celendar_event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('ix_comments_event_time', 'comments_event', ['event_id', 'time'], unique=False, schema='public')
    op.create_index('ix_comments_user', 'comments_event', ['user_id'], unique=False, schema='public')
    op.create_table('event_confirmends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('confirm_type', sa.Enum('DEFINITELY', 'PLANNING_TO', 'MIGHT_GO', 'DEFINITELY_NOT', name='accuracy'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['public.celendar_event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', name='uq_user_event_confirm'),
    schema='public'
    )
    op.create_index('ix_confirm_event', 'event_confirmends', ['event_id'], unique=False, schema='public')
    op.create_index('ix_confirm_type', 'event_confirmends', ['confirm_type'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_confirm_type', table_name='event_confirmends', schema='public')
    op.drop_index('ix_confirm_event', table_name='event_confirmends', schema='public')
    op.drop_table('event_confirmends', schema='public')
    op.drop_index('ix_comments_user', table_name='comments_event', schema='public')
    op.drop_index('ix_comments_event_time', table_name='comments_event', schema='public')
    op.drop_table('comments_event', schema='public')
    op.drop_table('tokens', schema='public')
    op.drop_table('friends', schema='public')
    op.drop_index(op.f('ix_public_celendar_event_event_date'), table_name='celendar_event', schema='public')
    op.drop_index('ix_calendar_user_date', table_name='celendar_event', schema='public')
    op.drop_index('ix_calendar_type', table_name='celendar_event', schema='public')
    op.drop_index('ix_calendar_planning', table_name='celendar_event', schema='public')
    op.drop_table('celendar_event', schema='public')
    op.drop_index('ix_users_is_banned', table_name='users', schema='public')
    op.drop_index('ix_users_account_nick', table_name='users', schema='public')
    op.drop_index('ix_users_account_name', table_name='users', schema='public')
    op.drop_index('ix_users_account_confirmed', table_name='users', schema='public')
    op.drop_index('ix_users_account_code', table_name='users', schema='public')
    op.drop_table('users', schema='public')
    # ### end Alembic commands ###
